# Generated by Django 4.2.30 on 2026-07-16 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_clear_graph_photo_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirement_view',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RequirementRepository',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('provider', models.CharField(default='github', max_length=64)),
                ('repo_url', models.CharField(max_length=1024)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=32)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_repository', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_requirement_repositories', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement Repository',
                'verbose_name_plural': 'Requirement Repositories',
                'db_table': 'requirement_repositories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uid', models.CharField(db_index=True, max_length=255)),
                ('node_type', models.CharField(default='REQUIREMENT', max_length=64)),
                ('file_path', models.CharField(max_length=1024)),
                ('title', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('field_values', models.JSONField(default=dict)),
                ('relations', models.JSONField(default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement',
                'verbose_name_plural': 'Requirements',
                'db_table': 'requirements',
                'ordering': ('file_path', 'sort_order'),
            },
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'file_path', 'uid'), name='requirement_unique_project_file_uid_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('project', 'file_path', 'uid', 'deleted_at')},
        ),
    ]
