# Generated by Django 4.2.30 on 2026-07-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_project_requirement_view_requirementrepository_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='document_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
