# Generated by Django 4.2.30 on 2026-07-16 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_requirement_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('title', models.TextField(blank=True, null=True)),
                ('commits', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Requirement Document',
                'verbose_name_plural': 'Requirement Documents',
                'db_table': 'requirement_documents',
                'ordering': ('file_path',),
            },
        ),
        migrations.AddConstraint(
            model_name='requirementdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'file_path'), name='requirement_document_unique_project_file_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementdocument',
            unique_together={('project', 'file_path', 'deleted_at')},
        ),
    ]
