# Generated by Django 4.2.30 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_service_desk_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedeskconfig',
            name='notify_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('ADMINS', 'Admins'), ('MEMBERS', 'Members'), ('CUSTOM', 'Custom')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='servicedeskconfig',
            name='notify_user_ids',
            field=models.JSONField(default=list),
        ),
    ]
