# Generated by Django 4.2.30 on 2026-07-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_requirementdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementrepository',
            name='co_author_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requirementrepository',
            name='co_author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
