# Generated by Django 4.2.30 on 2026-07-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_service_desk_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueemailmessage',
            name='attachments',
            field=models.JSONField(default=list),
        ),
    ]
